### ISSUE TITLE
Fractal config does not load as expected

### ISSUE THREAD

**Issue by FlorianBoe** [adamlindqvist/fractal-webpack-plugin#1]
Hi Adam,
I stumble over your project today and tried to use it in an existing project of mine. I noticed that my `fractal.js` configuration file was not loaded correctly. I am not very familiar with node.js, but I found the following solution for this problem: Within the try catch statement I had to use node.js path resolve method to get the absolute path of the configuration file.

```
try {
    var fractal = require(path.resolve('./fractal.js'));
} catch (e) {
    var fractal = require('@frctl/fractal').create();
}
```

This addition may only be necessary because I override some default options within my webpack configuration and my build scripts are located in folder called `lib` and not in the project root. However it might be useful for other use cases to add the path of the configuration as an option and allow the configuration file to be positioned somewhere else in the project structure.

**Comment by adamlindqvist** [comment]
Hi @FlorianBoe,

That was a great suggestion!
I will have a look and try to add an option to configure the path for the fractal.js file asap.

Thanks!

**Comment by thescientist13** [comment]
@adamlindqvist 
Just stumbled across this as well.  Having an option to configure _fractal.js_ path (in my case in the root for my project) would be great!

**Comment by thescientist13** [comment]
This worked well for me to resolve a _fractal.js_ at the root of the project
```javascript
var fractal = require(path.resolve(process.cwd(), 'fractal.js')).create();
```

(I could make a PR if you like)

Great plugin btw, it's working great! 🙏

**Comment by thescientist13** [comment]
it may also be worth considering `@fractcal` as a `peerDependency`.  This would allow the version of fractal being used to be one that can be specified by the consumer, instead of tied to this plugin.  Just a thought.

**Comment by thescientist13** [comment]
I've to a working implementation you can test out here that I got working for my project.
https://github.com/thescientist13/fractal-webpack-plugin/tree/resolve-local-fractal-config

**Comment by adamlindqvist** [comment]
Hi. Sorry for the delay. I just came back from vacation.

Thanks alot for your help @thescientist13. I have pushed and tagged a minor release with the changes you suggested. 

I will also start work on a new release where the fractal.js path will be fully configurable.

**Comment by adamlindqvist** [comment]
@FlorianBoe FYI. A new version has been released with the option to configure the path to fractal.js.

**Comment by thescientist13** [comment]
it's working well, thanks @adamlindqvist !

**Comment by FlorianBoe** [comment]
Hi @adamlindqvist,
I've also just returned from a little vacation. Today I found the time to test the new version, it works as expected. Thanks!
