### ISSUE TITLE
Look for fractal.config.js by default

### ISSUE THREAD

**Issue by ckrack** [adamlindqvist/fractal-webpack-plugin#11]
Hi Adam, ``fractal:1.3.0`` renamed the ``fractal.js`` file to ``fractal.config.js``.
It'd be good to look for this as an additional default.

**Comment by adamlindqvist** [comment]
Hi @ckrack, I'm sorry for the delay.

This has been updated from v4.1.3 in this plugin (https://www.npmjs.com/package/fractal-webpack-plugin).
